[project]
org-name= "roland"
version= "0.1.0"

[build-options]
observability-included=true

[dependencies]

[platform]
target = "java8"

  [[platform.libraries]]
  module = "java.jms"
  path = "../utils/target/jms-utils-0.99.0.jar"
  artifactId = "jms-utils"
  version = "0.99.0"
  groupId = "org.ballerinalang"

  [[platform.libraries]]
  module = "java.jms"
  path = "../utils/target/classes/lib/javax.jms-api-2.0.1.jar"
  artifactId = "javax.jms-api"
  version = "2.0.1"
  groupId = "javax.jms"