[project]
org-name= "roland"
version= "0.1.0"

[build-options]
observability-included=true

[dependencies]
"ballerina/java.jms" = { path = "./javalibs/java.jms-2020r2-java8-0.99.0.balo", version = "0.99.0"}

[platform]
target = "java8"

   [[platform.libraries]]
   path = "./javalibs/azure-servicebus-1.2.8.jar"
   modules = ["jms_queue_module"]

   [[platform.libraries]]
   path = "./javalibs/qpid-jms-client-0.27.0.jar"
   modules = ["jms_queue_module"]

   [[platform.libraries]]
   path = "./javalibs/proton-j-0.23.0.jar"
   modules = ["jms_queue_module"]

   [[platform.libraries]]
   path = "./javalibs/log4j-1.2.8.jar"
   modules = ["jms_queue_module"]

   [[platform.libraries]]
   path = "./javalibs/slf4j-log4j12-1.7.25.jar"
   modules = ["jms_queue_module"]

   [[platform.libraries]]
   path = "./javalibs/commons-cli-1.4.jar"
   modules = ["jms_queue_module"]

   [[platform.libraries]]
   path = "./javalibs/junit-4.12.jar"
   modules = ["jms_queue_module"]

   [[platform.libraries]]
   module = "jms_queue_module"
   path = "./javalibs/geronimo-j2ee-management_1.1_spec-1.0.1.jar"
   artifactId = "geronimo-j2ee-management_1.1_spec"
   version = "1.0.1"
   groupId = "org.apache.geronimo.specs"

   [[platform.libraries]]
   module = "jms_queue_module"
   path = "./javalibs/libs/hawtbuf-1.11.jar"
   artifactId = "hawtbuf"
   version = "1.11"
   groupId = "org.fusesource.hawtbuf"

