[project]
org-name= "roland"
version= "0.1.0"

[build-options]
observability-included=true

[dependencies]

[platform]
target = "java8"

   [[platform.libraries]]
   path = "./javalibs/azure-servicebus-1.2.19-SNAPSHOT.jar"
   modules = ["asb_module"]
