[project]
org-name= "roland"
version= "0.1.0"

[build-options]
observability-included=true

[dependencies]

[platform]
target = "java8"

   [[platform.libraries]]
   path = "./javalibs/snakeyaml-1.25.jar"
   modules = ["yamlparser"]
